/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cloudream_ishow_algorithm_Feature */

#ifndef _Included_com_cloudream_ishow_algorithm_Feature
#define _Included_com_cloudream_ishow_algorithm_Feature
#ifdef __cplusplus
extern "C" {
#endif
#undef com_cloudream_ishow_algorithm_Feature_NATIVE
#define com_cloudream_ishow_algorithm_Feature_NATIVE 1L
/*
 * Class:     com_cloudream_ishow_algorithm_Feature
 * Method:    getSymmetryAxis
 * Signature: ([Landroid/graphics/PointF;)[Landroid/graphics/PointF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cloudream_ishow_algorithm_Feature_getSymmetryAxis
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
