/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cloudream_ishow_algorithm_FaceDetector */

#ifndef _Included_com_cloudream_ishow_algorithm_FaceDetector
#define _Included_com_cloudream_ishow_algorithm_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif
#undef com_cloudream_ishow_algorithm_FaceDetector_NATIVE
#define com_cloudream_ishow_algorithm_FaceDetector_NATIVE 1L
/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeDetectFaceSingle
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Landroid/graphics/PointF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeDetectFaceSingle
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeDetectFaceSingle2
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;)[Landroid/graphics/PointF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeDetectFaceSingle2
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeSeamlessClone
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/PointF;I)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeSeamlessClone
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeSeamlessClone2
 * Signature: (Ljava/lang/String;Ljava/lang/String;Landroid/graphics/PointF;I)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeSeamlessClone2
  (JNIEnv *, jclass, jstring, jstring, jobject, jint);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeDetect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Lcom/cloudream/ishow/algorithm/FaceDetector/RoiInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeDetect
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeCenterOfRegion
 * Signature: (I)Landroid/graphics/PointF;
 */
JNIEXPORT jobject JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeCenterOfRegion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeCalculateRegionInfo
 * Signature: (I)Lcom/cloudream/ishow/algorithm/FaceDetector/RoiInfo;
 */
JNIEXPORT jobject JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeCalculateRegionInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeStretchImage
 * Signature: (Lorg/opencv/core/Mat;Lorg/opencv/core/Mat;[Landroid/graphics/PointF;[Landroid/graphics/PointF;)Lorg/opencv/core/Mat;
 */
JNIEXPORT jobject JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeStretchImage
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeStretchImage2
 * Signature: (Lorg/opencv/core/Mat;II[Landroid/graphics/PointF;[Landroid/graphics/PointF;)Lorg/opencv/core/Mat;
 */
JNIEXPORT jobject JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeStretchImage2
  (JNIEnv *, jclass, jobject, jint, jint, jobjectArray, jobjectArray);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeOverlay
 * Signature: (Lorg/opencv/core/Mat;Lorg/opencv/core/Mat;III)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeOverlay
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeCloneFace
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/opencv/core/Mat;
 */
JNIEXPORT jobject JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeCloneFace
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeCreateBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeCreateBitmap
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    getSymmetryAxis
 * Signature: ([Landroid/graphics/PointF;Landroid/graphics/PointF;Landroid/graphics/PointF;)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_getSymmetryAxis
  (JNIEnv *, jclass, jobjectArray, jobject, jobject);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeBlendIris
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;F)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeBlendIris
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeBlendIris2
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;IF)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeBlendIris2
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray, jint, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeBlendBlusher
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;IF)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeBlendBlusher
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jint, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeBlendEyeBrow
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;[Landroid/graphics/PointF;F)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeBlendEyeBrow
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jobjectArray, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeBlendEyeLash
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;IF)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeBlendEyeLash
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jint, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_FaceDetector
 * Method:    nativeSquare
 * Signature: (Landroid/graphics/Bitmap;[Landroid/graphics/PointF;J)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_FaceDetector_nativeSquare
  (JNIEnv *, jclass, jobject, jobjectArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
