/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cloudream_ishow_algorithm_Makeup */

#ifndef _Included_com_cloudream_ishow_algorithm_Makeup
#define _Included_com_cloudream_ishow_algorithm_Makeup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cloudream_ishow_algorithm_Makeup
 * Method:    nativeApplyLipColor
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_Makeup_nativeApplyLipColor
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_Makeup
 * Method:    nativeApplyBlush
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;IIF)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_Makeup_nativeApplyBlush
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jint, jint, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_Makeup
 * Method:    nativeBlendIris
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;F)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_Makeup_nativeBlendIris
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_Makeup
 * Method:    nativeBlendIris2
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;IF)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_Makeup_nativeBlendIris2
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray, jint, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_Makeup
 * Method:    nativeBlendBlusher
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;IF)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_Makeup_nativeBlendBlusher
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jint, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_Makeup
 * Method:    nativeBlendEyeBrow
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;[Landroid/graphics/PointF;F)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_Makeup_nativeBlendEyeBrow
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jobjectArray, jfloat);

/*
 * Class:     com_cloudream_ishow_algorithm_Makeup
 * Method:    nativeBlendEyeLash
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;[Landroid/graphics/PointF;IF)V
 */
JNIEXPORT void JNICALL Java_com_cloudream_ishow_algorithm_Makeup_nativeBlendEyeLash
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
