/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wonderful_ishow_algorithm_Effect */

#ifndef _Included_com_wonderful_ishow_algorithm_Effect
#define _Included_com_wonderful_ishow_algorithm_Effect
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wonderful_ishow_algorithm_Effect_NATIVE
#define com_wonderful_ishow_algorithm_Effect_NATIVE 0L
/*
 * Class:     com_wonderful_ishow_algorithm_Effect
 * Method:    nativeApplyWhirlPinch
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Point;FFF)V
 */
JNIEXPORT void JNICALL Java_com_wonderful_ishow_makeup_Effect_nativeApplyWhirlPinch
  (JNIEnv *, jclass, jobject, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_wonderful_ishow_algorithm_Effect
 * Method:    nativeApplyWhirlPinch2
 * Signature: (Landroid/graphics/Bitmap;FFF)V
 */
JNIEXPORT void JNICALL Java_com_wonderful_ishow_makeup_Effect_nativeApplyWhirlPinch2
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_wonderful_ishow_algorithm_Effect
 * Method:    nativeDistort
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/PointF;Landroid/graphics/PointF;FI)V
 */
JNIEXPORT void JNICALL Java_com_wonderful_ishow_makeup_Effect_nativeDistort
  (JNIEnv *, jclass, jobject, jobject, jobject, jfloat, jint);

/*
 * Class:     com_wonderful_ishow_algorithm_Effect
 * Method:    nativeCatmullRomSpline
 * Signature: (Landroid/graphics/PointF;FLandroid/graphics/PointF;Landroid/graphics/PointF;Landroid/graphics/PointF;Landroid/graphics/PointF;)V
 */
JNIEXPORT void JNICALL Java_com_wonderful_ishow_makeup_Effect_nativeCatmullRomSpline
  (JNIEnv *, jclass, jobject, jfloat, jobject, jobject, jobject, jobject);

/*
 * Class:     com_wonderful_ishow_algorithm_Effect
 * Method:    nativeTone
 * Signature: (Landroid/graphics/Bitmap;IF)V
 */
JNIEXPORT void JNICALL Java_com_wonderful_ishow_makeup_Effect_nativeTone
  (JNIEnv *, jclass, jobject, jint, jfloat);

/*
 * Class:     com_wonderful_ishow_algorithm_Effect
 * Method:    nativeGrayToAlpha
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_wonderful_ishow_makeup_Effect_nativeGrayToAlpha
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_wonderful_ishow_algorithm_Effect
 * Method:    nativeColorToAlpha
 * Signature: (ILandroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_wonderful_ishow_makeup_Effect_nativeColorToAlpha
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     com_wonderful_ishow_algorithm_Effect
 * Method:    nativeSelectContiguousRegionByColor
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;IIFZZ)V
 */
JNIEXPORT void JNICALL Java_com_wonderful_ishow_makeup_Effect_nativeSelectContiguousRegionByColor
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jfloat, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
