/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wonderful_ishow_algorithm_Feature */

#ifndef _Included_com_wonderful_ishow_algorithm_Feature
#define _Included_com_wonderful_ishow_algorithm_Feature
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wonderful_ishow_algorithm_Feature_NATIVE
#define com_wonderful_ishow_algorithm_Feature_NATIVE 1L
/*
 * Class:     com_wonderful_ishow_algorithm_Feature
 * Method:    nativeDetectFace
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;Ljava/lang/String;)[Landroid/graphics/PointF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_wonderful_ishow_algorithm_Feature_nativeDetectFace
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_wonderful_ishow_algorithm_Feature
 * Method:    nativeDetectFaces
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;Ljava/lang/String;)[[Landroid/graphics/PointF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_wonderful_ishow_algorithm_Feature_nativeDetectFaces
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_wonderful_ishow_algorithm_Feature
 * Method:    nativeGetSymmetryAxis
 * Signature: ([Landroid/graphics/PointF;)[Landroid/graphics/PointF;
 */
JNIEXPORT jobjectArray JNICALL Java_com_wonderful_ishow_algorithm_Feature_nativeGetSymmetryAxis
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
